matrix:
  dist: bionic
  include:
    - name: run unit tests
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements/test.txt
      script:
        - pytest --cov-config=./.coveragerc --cov-report term-missing --cov haven
    - name: check for missing migrations
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements/test.txt
      script:
        - ./manage.py makemigrations --check --dry-run --settings=haven.settings.test
    - name: verify built JS files are up to date
      language: node_js
      node_js:
        - 10
      before_script:
        - npm install -g gulp-cli
      script:
        - pushd static
        - npm install
        - gulp
        - popd
        - git diff --exit-code --numstat
      after_failure:
        - openssl aes-256-cbc -K $encrypted_348ccfbd8aab_key -iv $encrypted_348ccfbd8aab_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy_key
        - ssh-add .travis/deploy_key
        - git add static/build/
        - git commit -m "Add auto-generated built JS files"
        - git remote add deploy git@github.com:alan-turing-institute/data-safe-haven-webapp.git
        - test $TRAVIS_EVENT_TYPE = "push" && git diff --exit-code && git push deploy HEAD:$TRAVIS_BRANCH
    - name: run deployment checks
      language: python
      python:
        - "3.7"
      env:
        - SECRET_KEY='notasecret'
      addons:
        apt:
          packages:
            - unixodbc-dev
      install:
        - pip install -r requirements/production.txt
      script:
        - ./manage.py check --deploy --settings=haven.settings.production