matrix:
  dist: bionic
  include:
    - name: run unit tests
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements/test.txt
      script:
        - pytest --cov-config=./.coveragerc --cov-report term-missing --cov haven
    - name: check for missing migrations
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements/test.txt
      script:
        - ./manage.py makemigrations --check --dry-run --settings=config.settings.test
    - name: verify built JS files are up to date
      language: node_js
      node_js:
        - 10
      before_script:
        - npm install -g gulp-cli
      script:
        - cd static
        - npm install
        - gulp
        - git diff --exit-code --numstat
    - name: run deployment checks
      language: python
      python:
        - "3.7"
      env:
        - SECRET_KEY='notasecret'
      addons:
        apt:
          packages:
            - unixodbc-dev
      install:
        - pip install -r requirements/production.txt
      script:
        - ./manage.py check --deploy --settings=haven.config.settings.production
