matrix:
  dist: bionic
  include:
    - language: python
      python:
        - "3.7"
      env:
        - PYTHONPATH=haven/
      install:
        - pip install -r requirements/test.txt
      script:
        - pytest --cov-config=haven/.coveragerc --cov-report term-missing --cov haven
    - language: node_js
      node_js:
        - 10
      before_script:
        - npm install -g gulp-cli
      script:
        - cd haven/static
        - npm install
        - gulp
        - git diff --exit-code --numstat
