matrix:
  dist: bionic
  include:
    - name: run unit tests
      language: python
      python:
        - "3.8"
      services:
        - postgresql
      before_install:
        - pip install poetry
      install:
        - poetry install
      env:
        - DATABASE_URL=pgsql://haven:haven@db:5432/haven
      before_script:
        - psql -c 'CREATE USER haven;' -U postgres
        - psql -c 'ALTER USER haven WITH CREATEDB;' -U postgres
      script:
        - poetry run pytest --cov-config=./.coveragerc --cov-report term-missing --cov haven
    - name: check for missing migrations
      language: python
      python:
        - "3.8"
      before_install:
        - pip install poetry
      install:
        - poetry install
      script:
        - ./manage.py makemigrations --check --dry-run --settings=haven.settings.test
    - name: verify built JS files are up to date
      language: node_js
      node_js:
        - 10
      before_script:
        - npm install -g gulp-cli
      script:
        - cd static
        - npm install
        - gulp
        - git diff --exit-code --numstat
    - name: run deployment checks
      language: python
      python:
        - "3.8"
      env:
        - SECRET_KEY='notasecret'
      addons:
        apt:
          packages:
            - unixodbc-dev
      before_install:
        - pip install poetry
      install:
        - poetry install --no-dev
      script:
        - ./manage.py check --deploy --settings=haven.settings.production
