version: "3.9"


services:
  db:
    image: postgres 
    ports:                      
      - '5432'
    container_name: test_deploy_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello
 
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db