version: "3.8"

services:
  db:
    image: postgres 
    ports:                      
      - '5432:5432'
    container_name: data_classification_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=haven
      - POSTGRES_USER=haven
      - POSTGRES_PASSWORD=haven
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: