version: '3.4'
services:

  app:
    build:
      context: .
      target: dev
#     volumes:
#       - .:/home/site/repository
    ports:
      - "${APP_BIND_ADDRESS}:8000"
    env_file: .env

  db:
    image: postgres:10.7
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  db_data:
