version: "3.8"

services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    container_name: data_classification_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=haven
      - POSTGRES_USER=haven
      - POSTGRES_PASSWORD=haven

  web:
    build: .
    image: haven_local_django
    container_name: django
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
