version: "3.3"

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: ./LetsencryptDockerfile
    container_name: nginx_letencrypt
    ports:
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
