version: "3.8"

services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    container_name: igapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.postgres

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: igapp_local_django
    container_name: igapp_django
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - db
    command: /start

volumes:
  postgres_data:
