version: "3.3"

services:
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # provide the key and cert to the postgres server
      # - ./ca/certs/server.crt:/var/lib/postgresql/server.crt
      #- ./ca/certs/server.key:/var/lib/postgresql/server.key
    ports:
      - '5432:5432'
     # ensure postgres is coming up with ssl mode on
     #command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgressql/server.key
    env_file:
      - ./.envs/.production/.postgres

  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ig_app_production_django
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    #restart: "on-failure"
    depends_on:
      - db
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: igapp_production_nginx
    container_name: igapp_nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.envs/.production/.django
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - static_volume:/app/staticfiles
      - ./compose/production/nginx/conf.d:/etc/nginx/conf.d
      - ./compose/production/nginx/includes:/etc/nginx/includes
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
      - db
      - authelia
    restart: always

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  authelia:
    image: authelia/authelia
    container_name: igapp_authelia
    volumes:
      - ./compose/production/authelia:/config
    ports:
      - 9091:9091
    env_file:
      - ./.envs/.production/.django
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_authelia
    volumes:
      - ./redis:/data
    expose:
      - 6379
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
