version: "3"

services:
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=haven
      - POSTGRES_USER=haven
      - POSTGRES_PASSWORD=haven

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate easyaudit &&
                    python manage.py migrate &&
                    gunicorn haven.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

volumes:
  postgres_data:


 
