# Generated by Django 2.1 on 2019-05-14 13:31

from django.db import migrations, models
import django.db.models.deletion

from data import classification


def insert_initial_questions(apps, schema_editor):
    ClassificationQuestion = apps.get_model('data', 'ClassificationQuestion')
    classification.insert_initial_questions(ClassificationQuestion)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20181220_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('question', models.TextField()),
                ('yes_tier', models.IntegerField(blank=True, choices=[(0, 'Tier 0'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], null=True)),
                ('no_tier', models.IntegerField(blank=True, choices=[(0, 'Tier 0'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], null=True)),
                ('no_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data.ClassificationQuestion')),
                ('yes_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data.ClassificationQuestion')),
            ],
        ),
        migrations.RunPython(insert_initial_questions, migrations.RunPython.noop),
    ]
