# Generated by Django 2.1 on 2019-07-03 10:50

from django.db import migrations
from simple_history.manager import HistoryManager
from simple_history.models import HistoricalRecords


def fix_typo(apps, schema_editor):
    ClassificationQuestion = apps.get_model('data', 'ClassificationQuestion')
    HistoricalClassificationQuestion = apps.get_model('data', 'HistoricalClassificationQuestion')
    q = ClassificationQuestion.objects.get(name='publishable')
    q.question=('Could all the data handled or generated be published, '
                'albeit at the loss of research competitiveness?')
    q.save()
    manager = HistoryManager(HistoricalClassificationQuestion)
    q.history = manager
    history = HistoricalRecords()
    history.manager_name='history'
    history.cls=ClassificationQuestion.__class__
    history.post_save(q, created=False)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_historicalclassificationquestion'),
    ]

    operations = [
        migrations.RunPython(fix_typo),
    ]
