# Generated by Django 2.1 on 2019-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_dataset_default_representative'),
        ('data', '0009_auto_20190703_1050'),
    ]

    operations = [
    ]
