# Generated by Django 2.1 on 2019-07-29 14:09

from django.db import migrations, models

from haven.data import classification
from haven.data.tiers import Tier


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_merge_20190716_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationquestion',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclassificationquestion',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
