# Generated by Django 2.1 on 2019-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190729_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationGuidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('guidance', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='classificationquestion',
            name='guidance',
            field=models.ManyToManyField(related_name='questions', to='data.ClassificationGuidance'),
        ),
    ]
