# Generated by Django 2.1 on 2019-08-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20190801_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationquestion',
            name='guidance',
        ),
    ]
