# Generated by Django 3.1.13 on 2022-05-04 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
