# Generated by Django 3.1.13 on 2022-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_dataset_uuid_unique_non_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='host',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='storage_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
