# Generated by Django 3.1.13 on 2022-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_add_host_and_storage_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalclassificationquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classification question', 'verbose_name_plural': 'historical classification questions'},
        ),
        migrations.AlterField(
            model_name='historicalclassificationquestion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
