---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkYXRhY2xhc3NpZmljYXRpb25hcHAiLCJpYXQiOjE2NDQzOTg3NzMsImV4cCI6MTY3NTkzNDgxOSwiYXVkIjoiZGNhLnVrc291dGguY2xvdWRhcHAuYXp1cmUuY29tIiwic3ViIjoiYWRtaW51c2VyQGFkbWluLmNvbSJ9.wJVUxRIpbf0PcLGuixYX_EWuLiUwubfcr_DPfj-temM
default_redirection_url: https://dca.uksouth.cloudapp.azure.com/haven

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
  # should this be the domain?
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    #- domain: dca.uksouth.cloudapp.azure.com
     # policy: bypass
    - domain: dca.uksouth.cloudapp.azure.com
      policy: one_factor
    #- domain: dca.uksouth.cloudapp.azure.com
    #  policy: two_factor

# cookie settings
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: YBhhHp3QS9NWJNSUqbLDVK1dw2mIQ3DA
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: dca.uksouth.cloudapp.azure.com  # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m

storage:
  local:
    path: /config/db.sqlite3
  encryption_key : sBFJ3zoGVHzYH9ep3BuR

notifier:
  filesystem:
    filename: /config/notification.txt
  #smtp:
    #username: bexosselton@gmail.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    #password: password
    #host: dca.uksouth.cloudapp.azure.com
    #port: 25
    #sender: admin@example.com
...
