---
###############################################################
#                   Authelia configuration                    #
###############################################################

# Replace with a random alphanumeric string >64 characters in production
# https://www.authelia.com/configuration/miscellaneous/introduction/#jwt_secret
jwt_secret: v3ry_important_s3cr3t

default_redirection_url: https://${BASE_DOMAIN}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
  # should this be the domain?
  issuer: ${BASE_DOMAIN}

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: a_very_important_secret

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
        algorithm: argon2id
        iterations: 1
        salt_length: 16
        parallelism: 8
        memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: ${BASE_DOMAIN}
      policy: one_factor


# cookie settings
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # https://www.authelia.com/configuration/session/introduction/#secret
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: ${BASE_DOMAIN}  # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m

storage:
  local:
    path: /config/db.sqlite3
  # https://www.authelia.com/configuration/storage/introduction/#encryption_key
  encryption_key : a_very_important_secret

notifier:
  filesystem:
    filename: /config/notification.txt
  #smtp:
    #username: admin@example.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    #password: password
    #host: dca.example.com
    #port: 25
    #sender: admin@example.com
...
