# Generated by Django 2.1 on 2019-03-13 16:07

from django.db import migrations
import identity.managers


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_auto_20181231_1244'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', identity.managers.CustomUserManager()),
            ],
        ),
    ]
