# Generated by Django 2.1 on 2019-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_rename_programme_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('system_manager', 'System Manager'), ('programme_manager', 'Programme Manager'), ('', 'Standard user')], help_text="The user's role in the system", max_length=50),
        ),
    ]
