# Generated by Django 2.1 on 2018-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_research_coordinator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Tier 0'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], null=True),
        ),
    ]
