# Generated by Django 2.1 on 2019-06-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_historicalclassificationquestion'),
        ('projects', '0012_auto_20190619_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationOpinionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('question_version', models.IntegerField()),
                ('answer', models.BooleanField()),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.ClassificationOpinion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data.ClassificationQuestion')),
            ],
        ),
    ]
