# Generated by Django 2.1 on 2019-07-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def insert_packages(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    WorkPackage = apps.get_model('projects', 'WorkPackage')
    for p in Project.objects.all():
        wp = WorkPackage(
            project=p,
            name='Ingest',
            description='Initial ingest of data',
            created_by=p.created_by,
        )
        wp.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_classificationopinionquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the work package was added to the project')),
                ('created_by', models.ForeignKey(help_text='User who added this work package to the project', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.RunPython(insert_packages, migrations.RunPython.noop),
    ]
