# Generated by Django 2.1 on 2019-07-08 14:02

from django.db import migrations, models
import django.db.models.deletion


def update_classifications(apps, schema_editor):
    WorkPackage = apps.get_model('projects', 'WorkPackage')
    ClassificationOpinion = apps.get_model('projects', 'ClassificationOpinion')
    for co in ClassificationOpinion.objects.all():
        wp = WorkPackage.objects.filter(project=co.project).first()
        co.work_package = wp
        co.save()
    for wp in WorkPackage.objects.all():
        wp.tier = wp.project.tier
        wp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_workpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationopinion',
            name='work_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='projects.WorkPackage'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Tier 0'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='projects.Project'),
        ),
        migrations.RunPython(update_classifications, migrations.RunPython.noop),
    ]
