# Generated by Django 2.1 on 2019-07-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20190708_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tier',
        ),
        migrations.AlterField(
            model_name='classificationopinion',
            name='work_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='projects.WorkPackage'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationopinion',
            unique_together={('user', 'work_package')},
        ),
    ]
