# Generated by Django 2.1 on 2019-07-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190708_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationopinion',
            name='project',
        ),
    ]
