# Generated by Django 2.1 on 2019-07-09 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_datasets(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectDataset = apps.get_model('projects', 'ProjectDataset')
    for p in Project.objects.all():
        for d in p.datasets.all():
            pd = ProjectDataset(project=p, dataset=d, created_by=p.created_by)
            pd.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_dataset_default_representative'),
        ('projects', '0017_remove_classificationopinion_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the dataset was added to the project')),
                ('created_by', models.ForeignKey(help_text='User who added this dataset to the project', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='datasets2',
            field=models.ManyToManyField(blank=True, related_name='projects2', through='projects.ProjectDataset', to='data.Dataset'),
        ),
        migrations.RunPython(copy_datasets, migrations.RunPython.noop)
    ]
