# Generated by Django 2.1 on 2019-07-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_dataset_default_representative'),
        ('projects', '0021_projectdataset_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackageDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the dataset was added to the work package')),
                ('created_by', models.ForeignKey(help_text='User who added this dataset to the work package', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Dataset')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.WorkPackage')),
            ],
        ),
        migrations.AddField(
            model_name='workpackage',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='work_packages', through='projects.WorkPackageDataset', to='data.Dataset'),
        ),
    ]
