# Generated by Django 2.1 on 2019-07-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190709_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackagedataset',
            name='opinion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='projects.ClassificationOpinion'),
        ),
    ]
