# Generated by Django 2.1 on 2019-08-06 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_workpackagedataset_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdataset',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
