# Generated by Django 2.1 on 2019-09-02 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190902_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='projectdataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectdataset',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackagedataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='workpackagedataset',
            name='opinion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.ClassificationOpinion'),
        ),
        migrations.AlterField(
            model_name='workpackagedataset',
            name='work_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.WorkPackage'),
        ),
    ]
