# Generated by Django 2.1 on 2019-09-02 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0016_remove_classificationquestion_guidance'),
        ('projects', '0028_auto_20190902_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackageParticipantApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Dataset')),
                ('work_package_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.WorkPackageParticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
