# Generated by Django 2.1 on 2019-10-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_workpackageparticipantapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackageparticipantapproval',
            name='work_package_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.WorkPackageParticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='workpackageparticipant',
            unique_together={('participant', 'work_package')},
        ),
    ]
