# Generated by Django 2.1 on 2019-11-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_classificationquestion_guidance'),
        ('projects', '0031_auto_20191021_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workpackagedataset',
            unique_together={('work_package', 'dataset')},
        ),
    ]
