# Generated by Django 2.1 on 2019-11-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20191111_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_datasets', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='workpackagedataset',
            name='work_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_package_datasets', to='projects.WorkPackage'),
        ),
    ]
