# Generated by Django 2.1 on 2020-01-16 16:34

from django.db import migrations, models


def set_state(apps, schema_editor):
    WorkPackage = apps.get_model('projects', 'WorkPackage')

    for wp in WorkPackage.objects.all():
        if wp.tier is not None:
            wp.status = 'classified'
            wp.save()
        elif wp.classifications.exists():
            wp.status = 'underway'
            wp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20191205_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('underway', 'Classification Underway'), ('classified', 'Classified')], default='new', max_length=32),
        ),
        migrations.RunPython(set_state, migrations.RunPython.noop)
    ]
