# Generated by Django 3.1.13 on 2022-05-31 13:03

from django.db import migrations, models
import django.db.models.deletion
import haven.data.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_classificationguidance_question_set'),
        ('projects', '0037_add_question_set_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='question_set',
            field=models.ForeignKey(default=haven.data.models.ClassificationQuestionSet.get_default_id, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='data.classificationquestionset'),
        ),
    ]
