# Generated by Django 3.1.13 on 2022-05-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_classificationguidance_question_set'),
        ('projects', '0042_project_uuid_unique_non_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='question_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='data.classificationquestionset'),
        ),
    ]
